### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/infografia-mae18-25#1]
[Infografía (1).pdf](https://github.com/user-attachments/files/16791549/Infografia.1.pdf)

**Comment by Eddi3mendoz** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:14/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:12/14
Presentación Visual:13/14
Referencias:5/14
Presentación:13/14
Calificación Final: 16.8/20
Califico: Edwin Eduardo Mendoza Cruz

**Comment by josealfredo79** [comment]
revisado..
